trigger:
  # start a new build for every push
  batch: False
  branches:
    include:
      - develop
  paths:
    include:
      - '*'

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string


jobs:
- job: Windows
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))  # skip for PR merges
  pool:
    vmImage: 'VS2017-Win2016'
  strategy:
    maxParallel: 4
    matrix:
        Python37-32bit-full:
          PYTHON_VERSION: '3.7'
          PYTHON_ARCH: 'x86'
          BITS: 32
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      addToPath: true
      architecture: $(PYTHON_ARCH)
  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: >-
      python -m pip install
      cython
      matplotlib
      numpy
      pytest
      pytest-xdist
      scikit-learn
      scipy
    displayName: 'Install dependencies'
  - powershell: |
      cd package
      python setup.py install
      cd ..\testsuite
      python setup.py install
      cd ..
    displayName: 'Build MDAnalysis'
  - powershell: |
      cd testsuite
      pytest .\MDAnalysisTests --disable-pytest-warnings -n 2 -rsx
    displayName: 'Run MDAnalysis Test Suite'

- job: Linux_Python_36_32bit
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
           docker pull i386/ubuntu:bionic
           docker run -v $(pwd):/mdanalysis i386/ubuntu:bionic /bin/bash -c "cd mdanalysis && \
           apt-get -y update --fix-missing && \
           apt-get -y install locales python3 python3-pip libfreetype6-dev && \
           locale-gen en_US.UTF-8 && \
           export LANG=en_US.UTF-8 && \
           export LC_ALL=en_US.UTF-8 && \
           python3 -m pip install --user --upgrade pip setuptools && \
           python3 -m pip install --user --upgrade pytest pytest-xdist && \
           python3 -m pip install --user --upgrade gsd cython numpy scipy hypothesis && \
           cd /mdanalysis/package && \
           python3 setup.py install --user && \
           cd /mdanalysis/testsuite && \
           python3 setup.py install --user && \
           /root/.local/bin/pytest --disable-pytest-warnings --durations=50 ./MDAnalysisTests"
    displayName: 'Run 32-bit Ubuntu Docker Build / Tests'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Publish test results for Python 3.6-32 bit Linux'
